disabled_rules:
  - identifier_name
  - todo
  - force_cast
  - trailing_whitespace
  - colon
  - type_name
  - comma
  - line_length
  - opening_brace
  - function_parameter_count
  - cyclomatic_complexity
excluded:
  - Carthage
  - Pods
function_body_length:
  - 230
  - 300
type_body_length:
  - 300
  - 600
variable_name_max_length:
  - 30
  - 50
file_length:
  - 500
  - 700
